### ISSUE TITLE
PAN-OS Network Operations - Upgrade Assurance - First Snapshot Failure

### ISSUE THREAD

**Issue by zallez123** [PaloAltoNetworks/xsoar-panos-upgrade-automation#39]
## Describe the bug

Experiencing a failure with XSOAR playbook associated with Panorama Batch Firewall Upgrades within a sub playbook "PAN-OS Network Operations - Upgrade Assurance - First Snapshot".
 
This sub playbook stems from a main playbook "PAN-OS Network Operations - Device Upgrade". This is documented as a supported playbook, and it is recommended from Palo.
 
We have filled in the correct firewall device name and serial number within our panorama, and we have confirmed integrations on the panorama side as well as firewall readiness.
 
We verified on our end that our DNS records were consistent. The input still returns the same error code (Temporary failure in name resolution):
 

## Expected behavior

Retrieve firewall devices to determine upgrade readiness. 

## Current behavior

Results in a temporary failure in name resolution. Associated log information below. AN_OS_Upgrade_Assurance returned an error
#125: Run Readiness Tests
Command:
!pan-os-assurance-run-readiness-checks firewall_serial="113101014803" check_session_exists="wuxppan10/tfw20/443"
(PAN_OS_Upgrade_Assurance)
Reason
URLError: reason: [Errno -3] Temporary failure in name resolution
 
Ran into programming error during implemenetation stages:
 
Exception message is [Traceback (most recent call last):
File "/tmp/pyrunner/_script_docker_python_loop.py", line 735, in <module>
exec(code, sub_globals, sub_globals)
File "<string>", line 12736, in <module>
File "<string>", line 12722, in main
File "<string>", line 12665, in command_run_readiness_checks
File "<string>", line 12598, in run_readiness_checks
TypeError: can only concatenate str (not "list") to str

## Screenshots

![image](https://github.com/user-attachments/assets/505f0058-deda-4872-b4a3-58ef0fa1b185)

![Screenshot 2024-08-07 133146](https://github.com/user-attachments/assets/91f28da1-7bbb-4656-ab13-51a4d4ddfdc5)

## Your Environment

- Version used: 8.7
- Desktop Win 10

**Comment by alperenkose** [comment]
`TypeError: can only concatenate str (not "list") to str` issue should be fixed now in the main branch with the #29 - but a release is not available yet.
Regarding the `URLError: reason: [Errno -3] Temporary failure in name resolution` issue, `check_session_exists` works on IPv4 addresses for checking existing sessions on the firewall in the output of `show sessions all` command.
Could you please try with the following format from the latest code ?
`check_session_exists="10.10.10.10/192.168.10.10/443"`

**Comment by alperenkose** [comment]
Closing the case. Original TypeError issue should be fixed. Name resolution issue doesn't seem to be related to this case.
